# Generated by Django 2.2.12 on 2020-05-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_sources_out_of_order_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='dark',
            field=models.BooleanField(default=False),
        ),
    ]
