# Generated by Django 2.1.2 on 2018-11-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0004_auto_20181003_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcolumnmap',
            name='provider_type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('OCP', 'OCP')], default='AWS', max_length=50),
        ),
    ]
