# Generated by Django 2.1.7 on 2019-03-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_common', '0007_auto_20190208_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='costusagereportstatus',
            name='ingest_started_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
