# Generated by Django 2.1.2 on 2018-11-13 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0016_delete_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('metric', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=6, max_digits=25)),
                ('timeunit', models.CharField(choices=[('nil', 'nil'), ('hour', 'hour'), ('minute', 'minute'), ('second', 'second'), ('day', 'day'), ('month', 'month'), ('year', 'year'), ('onetime', 'onetime')], default=('nil', 'nil'), max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('metric', 'price', 'timeunit')},
        ),
    ]
