# Generated by Django 2.1.2 on 2018-11-13 19:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0017_auto_20181113_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='provider_uuid',
            field=models.UUIDField(default=None),
        ),
        migrations.AddField(
            model_name='rate',
            name='rates',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rate',
            name='metric',
            field=models.CharField(choices=[('cpu_core_per_hour', 'cpu_core_per_hour'), ('memory_byte_per_hour', 'memory_byte_per_hour')], default='cpu_core_per_hour', max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='price',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='timeunit',
        ),
    ]
