# Generated by Django 2.2 on 2019-05-10 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0061_auto_20190501_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awscostentry',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.AWSCostEntryBill'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitem',
            name='cost_entry_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.AWSCostEntryBill'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdaily',
            name='cost_entry_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.AWSCostEntryBill'),
        ),
        migrations.AlterField(
            model_name='awscostentrylineitemdailysummary',
            name='cost_entry_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.AWSCostEntryBill'),
        ),
        migrations.AlterField(
            model_name='ocpawscostlineitemdailysummary',
            name='cost_entry_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.AWSCostEntryBill'),
        ),
        migrations.AlterField(
            model_name='ocpawscostlineitemprojectdailysummary',
            name='cost_entry_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.AWSCostEntryBill'),
        ),
    ]
